import { Bugpilot } from "@bugpilot/plugin-nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({
  subsets: ["latin"]
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <html lang="en">
      <body className={inter.className}>{children}<Bugpilot workspaceId="6c8f7177-9f52-4869-ba98-21d864f14af2" /></body>
    </html>;
}